### ISSUE TITLE
Getting format error when using docker image

### ISSUE THREAD

**Issue by Preston1299** [prometheus/busybox#11]
Im getting an "exec format error" when executing a docker file that uses a base image. 

``` Dockerfile
FROM quay.io/prometheus/busybox:latest
COPY apache_exporter.go /bin/apache_exporter
EXPOSE 9117
ENTRYPOINT ["/bin/apache_exporter"]

```
I seem to get this error whenever I import from the base image. I am running on Ubuntu. Any help would be much appreciated.

**Comment by sdurrheimer** [comment]
You can't copy a go file as a binary, you need to compile it first.
