### ISSUE TITLE
/etc/hosts ignored

### ISSUE THREAD

**Issue by 2solt** [prometheus/busybox#13]
Looks like docker images based on `prom/busybox` like `prom/alertmanager` ignoring /etc/hosts entries

Could you guys add the following to the Dockerfile ? :

`echo 'hosts: files dns' >> /etc/nsswitch.conf`

**Comment by brian-brazil** [comment]
Go DNS is just DNS, it doesn't use gethostbyname and thus Prometheus and Alertmanger do not use the contents of nsswitch.conf. Changing this file is probably not what you want.

**Comment by SuperQ** [comment]
CoreDNS has a [/etc/hosts plugin](https://coredns.io/plugins/hosts/). that can be used to solve this.

**Comment by SuperQ** [comment]
Go DNS does support `nsswitch.conf` and reading from `/etc/hosts` this way. The missing bit is the nsswitch.conf in the Dockerfile.  I'm not sure that's enough, as it would still need the hosts file mapped in as well.

**Comment by 2solt** [comment]
Tested, and looks like it works with `nsswitch.conf`, docker uses the hots /etc/hosts file

**Comment by brian-brazil** [comment]
That's new, when did this change?

**Comment by 2solt** [comment]
Closing as #16
