### ISSUE TITLE
Add an init process to image

### ISSUE THREAD

**Issue by jkemp101** [prometheus/busybox#14]
In my opinion, docker containers should be run with pid 1 being a process that is properly outfitted to act as an init process.  [Tini](https://github.com/krallin/tini) is a likely candidate to fill this role.  This ensures the nuances of running as pid 1 like handling signals the right way isn't left to the implementor's code.  I'm working through a related issue with the statsd exporter where the docker container exit code is `2` when terminated by `SIGTERM` instead of `143` or `0`, see https://github.com/prometheus/statsd_exporter/issues/133.  Could Tini or a similar init process be added to the base image to address this issue?

**Comment by matthiasr** [comment]
Is doing this within the container the right approach though? Now that there is `docker run --init`, it seems to me that this is the canonical way, and also gives users the choice.

**Comment by jkemp101** [comment]
When do you not want a proper init process?  This is the base image for prometheus projects so by not providing an init process in this image doesn't that mean you are asking each project that uses this image to either 1. add that functionality to their code, 2. add an init process like tini themselves, or 3. run the image with non-default `docker` command flags (e.g. `--init`)?

**Comment by matthiasr** [comment]
For example, when I run Docker with `--init`, or the container in Kubernetes with a container runtime that does provide an init anyway.

I don't think we should value "supporting docker with default flags" over the everything else.

**Comment by matthiasr** [comment]
Also, I presume Docker just can't turn this on by default because they would break every container that insists on running its own init.

**Comment by SuperQ** [comment]
I don't think we're going to do this. Handling signals is something that should be done as part of the exporter-toolkit these days.
