### ISSUE TITLE
Auto-build on upstream releases

### ISSUE THREAD

**Issue by SuperQ** [prometheus/busybox#28]
We should automatically re-build the lastest release when the upstream busybox releases happen.

We can use a CircleCI cron job for this.

**Comment by J0WI** [comment]
This does also affect all images in https://hub.docker.com/u/prom. They all run on an ancient BusyBox version with obsolete CA certificates and timezones.

**Comment by discordianfish** [comment]
What about building our own busybox image from scratch instead? Gives us more flexibility and shouldn't really be harder.

**Comment by J0WI** [comment]
[Upstream](https://hub.docker.com/_/busybox/) builds the image for various architectures, multiple C libraries and release channels. I'm not sure if it's worth to duplicate this work.
