### ISSUE TITLE
Add tzdata package

### ISSUE THREAD

**Issue by grobinson-grafana** [prometheus/busybox#61]
Some users have reported that `TZ` environment variable does not work in Alertmanager or Prometheus docker images.

- https://github.com/prometheus/alertmanager/issues/3810
- https://github.com/prometheus/prometheus/issues/13937

I think the issue is that the `tzdata` package is not installed. Should we?

**Comment by SuperQ** [comment]
Prometheus [only work in UTC](https://prometheus.io/docs/introduction/faq/#can-i-change-the-timezone-why-is-everything-in-utc), so changing the `TZ` env var is going to do nothing.

I'm not sure this will make any difference.

**Comment by grobinson-grafana** [comment]
Thanks! I'll close this then (I didn't know about the FAQ) and leave a comment on the original issue.
